#!/bin/bash

E_BADARGS=65

if [[ $# -ne 10 ]]
then
cat <<EOF
Parameters are:
    path-to-sound-file
    size-of-FFT
    PVOC-window-size (as multiple of FFT-size)
    hop-size
    number-of-NMF-components
    number-of-NMF-interations
    number-of-components-to-remove
    extrema-flag (1 = remove maxima, -1 = remove minima)
    trim-offset
    trim-length
EOF
exit $E_BADARGS
fi

pvocpath=~/Documents/development/portnoff_pvoc/test/bin

sox $1 -t f64 -c 1 -r 44.1k - trim $9 ${10} | \
    ${pvocpath}/pstft_analy_test $2 $3 $4| \
    ./nmf_process_remove_extrema stdin $2 $5 $6 $7 $8 | \
    ${pvocpath}/pstft_synth_test  $2 $4 $3 | \
    sox -t f64 -r 44.1k -c 1 - -d
