#!/bin/bash

E_BADARGS=65

if [[ $# -ne 11 ]]
then
cat <<EOF
Parameters are:
    path-to-sound-file
    size-of-FFT
    PVOC-window-size (as multiple of FFT-size)
    hop-size
    number-of-NMF-components
    number-of-NMF-interations
    spectral-discontinuity-threshold
    extrema-flag :
         1  = remove those exceeding threshold 
        -1  = remove those under threshold
    method-flag :
         1  = remove discontinuous frequency axis components
         2  = remove discontinuous time axis components
    trim-offset
    trim-length
EOF
exit $E_BADARGS
fi

pvocpath=~/Documents/development/portnoff_pvoc/test/bin

sox $1 -t f64 -c 1 -r 16k - trim ${10} ${11} | \
    ${pvocpath}/pstft_analy_test $2 $3 $4| \
    ./nmf_process_remove_spec_dis stdin $2 $5 $6 $7 $8 $9 | \
    ${pvocpath}/pstft_synth_test  $2 $4 $3 | \
    sox -t f64 -r 16k -c 1 - -d
